whittle-org/whittle

test/test_parameters.py
whittle/metrics/parameters.py

 Functionality to compue parameters of subnetworks

---

.github/workflows/run-examples.yml
.github/workflows/unit-test.yml
CONTRIBUTING.md
examples/sinc/search.py
examples/sinc/sinc_nas.py
poetry.toml
pyproject.toml
whittle/models/gpt/__init__.py

None
* Removes the need for `poetry` and instead just uses `pip`.
* Adds a slight contributing guide which is really at the moment just a reference.
* Fixes some namespacing module thing and hacks used for the examples to work. 
* Do a clean install of the library following `CONTRIBUTING.md`
* Docs are a follow up PR
* **I removed the lock-file**, lock files are only required experiments, reproducibility and applications. _Python_ frameworks can not be build-reproducible without severely limiting the ability to use the framework with extra dependencies.
* If you've been using poetry, you might want to make a fresh environment using native tools
```bash
conda create blah
conda activate blah
conda create -p ./.venv
conda activate ./.vev
pip -m venv .venv
source ./.venv/bin/activate
uv venv …
```

ci: Remove poetry

---

README.md

Updating the `README.md` installation instructions and removing the structure
Closes #67

fix: update README.md with correct installation instructions and removing structure

---

release.sh
whittle/__init__.py

Adds code to read and output the version number.
---

fix: add version number

---

whittle/sampling/random_sampler.py

None
rng in sampler is not used and a new random state is used every time. This passes the random state when sampling a hyperparameter and ensures reproducibility
---

fix: set random state properly in sampler

---

whittle/sampling/random_sampler.py

#108 
use max min for numerical values in categories, raise a warning otherwise

fix random sampler

---

pyproject.toml
whittle/version

Fixes the commitizen version configuration by adding an entry to `pyproject.toml`

fix: commitizen configuration

---

pyproject.toml
whittle/version

Reverts whittle-org/whittle#115

Revert "fix: commitizen configuration"

---

pyproject.toml

fix: adding cz config

---

docs/index.md

#120 
add installation instruction to documentation
---

feat: add installation instruction to documentation

---

whittle/metrics/mag.py
whittle/metrics/parameters.py
whittle/models/gpt/model.py

We currently do not set random layers correctly in reset super network, this pr fixes this bug

fix: reset random layers in reset_super_network

---

.github/workflows/run-examples.yml
examples/profile/profile_flops.py
pyproject.toml
whittle/metrics/flops.py

feat: adding flops and macs profiling for subnets

---

examples/profile/profile_flops.py
examples/profile/profile_latency.py
test/test_flops.py
test/test_mag.py
test/test_parameters.py
whittle/metrics/__init__.py
whittle/metrics/flops.py
whittle/metrics/latency.py
whittle/metrics/mag.py
whittle/metrics/parameters.py

#142 
- Unify name of metrics
- adds unittests for `compute_flops`
---

fix: refactor names of metric

---

pyproject.toml

fix: update tokenizers in pyproject.toml

---

whittle/training_strategies/ats.py
whittle/training_strategies/base_strategy.py
whittle/training_strategies/random.py
whittle/training_strategies/random_linear.py
whittle/training_strategies/sandwich.py
whittle/training_strategies/standard.py

Allows to pass a fabric to super-network training strategies. This is necessary to run in distributed setting, which is required for #157 
---

feat: allows to pass fabric

---

.github/workflows/release.yml

fix: reworking `release.yml` to avoid clashing with branch protection rules

---

.github/workflows/release.yml

Reverts whittle-org/whittle#180

fix: Revert "fix: reworking `release.yml` to avoid clashing with branch protection rules"

---

.github/workflows/release.yml

fix: release workflow clash with branch protection rules

---

.github/workflows/release.yml
.github/workflows/unit-test.yml

ci: reusing unit-test.yml in release.yml

---

.github/workflows/release.yml
.github/workflows/unit-test.yml

Reverts whittle-org/whittle#186

fix: Revert "ci: reusing unit-test.yml in release.yml"

---

whittle/models/gpt/model.py

https://github.com/whittle-org/whittle/issues/156
- removed it from the setter
- call it in forward() depending on input_pos
---

fix: Remove rope_cache from max_seq_len setter

---

.github/workflows/docs.yml
.github/workflows/run-examples.yml
.github/workflows/unit-test.yml

feat: using uv caching

---

.pre-commit-config.yaml
whittle/eval/whittle_llms.py
whittle/models/gpt/blocks/causal_self_attention.py
whittle/models/gpt/utils.py
whittle/modules/rmsnorm.py
whittle/pretrain_super_network.py
whittle/search/local_search.py

title, updates ruff pre-commit workflow version and allows unsafe fixes

fix: formatting

---

test/test_distill_loss.py
test/test_training_strategies.py
whittle/args.py
whittle/distill.py
whittle/loss/kd_loss.py
whittle/loss/losses.py

Issue #238 - Incorporate knowledge distillation losses
Added L1, L2, reverse_kld, cosine similarity, and Jensen-Shannon Divergence losses as options for distillation loss
---

feat: Add new distill losses

---

whittle/lora_model/lora_qkv_linear.py

fix: optimize lora_qkv_linear

---

pyproject.toml
test/test_flops.py
whittle/evaluate_network.py
whittle/metrics/__init__.py
whittle/search_sub_networks.py

Removes all mentioning of DeepSpeed.

refactor: Remove DeepSpeed 

---

whittle/pretrain_super_network.py

This PR resolves #285 
This PR updates the supernet pretraining code to more closely match the pretraining script in litgpt 0.5.7. The changes are minimal and affect only logging.
---

chore: update pretraining script for litgpt 0.5.7

---

test/test_full_finetune.py
whittle/full_finetune.py
whittle/lora.py

This PR resolve #284 
This PR has minor refactors and changes in logging to keep the finetuning scripts up to date with LitGPT 0.5.7

refactor(finetuning): update finetuning for litgpt 0.5.7

---

whittle/training_strategies/ats.py
whittle/training_strategies/random.py
whittle/training_strategies/random_linear.py
whittle/training_strategies/sandwich.py

fix: remove unnecessary GPU to CPU synchronizations
