whittle-org/whittle

benchmarks/plm_pruning/bert.py
benchmarks/plm_pruning/data_wrapper/data_wrapper.py
benchmarks/plm_pruning/data_wrapper/data_wrapper_alpaca.py
benchmarks/plm_pruning/search_spaces.py
whittle/sampling/random_sampler.py
whittle/training_strategies/base_strategy.py

None
* Remove empty `setup.py` (everything is statically defined through `pyproject.toml`)
* Removes the need to download the `setup.py` to figure out dynamic project specification which makes installation and dependancy resolution faster for dependant libraries)
* Remove inheretance from `object`. All classes inherently inhereit from this since Python 3 in so called "new style classes".
---

refactor: Remove dead `setup.py` file and Python 2 artifacts

---

.github/workflows/docs.yml
CONTRIBUTING.md
docs/_scripts/api_generator.py
docs/_scripts/clean_log_output.py
docs/_scripts/debug_which_page_is_being_rendered.py
docs/contributing.md
docs/index.md
mkdocs.yaml
pyproject.toml

None
* Uses `mkdocs` (`mkdocs-material`) to generate documentation. Right now there's just a dummy `index.md` with some examples on writing documentation.
* Generates `API` documentation automatically.
* Added a page for `contributing.md` which links to `CONTRIBUTING.md` in the root.
* Workflow to make sure docs render (non-strict)
```bash
pip install -e ".[dev]"
mkdocs serve
```
---

doc: Setup documentation

---

whittle/loss/kd_loss.py
whittle/training_strategies/ats.py
whittle/training_strategies/base_strategy.py
whittle/training_strategies/random.py
whittle/training_strategies/random_linear.py
whittle/training_strategies/sandwich.py

We call .detach() only in the loss function to allow to pass other loss functions than KDLoss. This is necessary for example for pruning BERT models.
---

fix: allow to pass other loss function to training strategies

---

.github/workflows/pr-conventional-commit.yml
.github/workflows/release.yml
.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml

Adds an automatic release workflow
Changes: 
- adding `commitizen` as a development dependency
- adding `commitizen` as a pre-commit hook
- adding `pr-conventional-commits.yml`: a GH action to check whether the PR title conforms to conventional commits
TODOs: 
Closes #92

ci: automatic release workflow

---

test/test_api.py
whittle/metrics/mag.py
whittle/metrics/parameters.py

Layer norm layer can be none when sharing layer norms in the transformer blocks (for phi-2), this PR simply returns zero as magnitude, num_params when the layer norm layer is none 
Tests to generate text is also updated, to add an additional space: Check this faliure of lm-eval -harness https://github.com/EleutherAI/lm-evaluation-harness/actions/runs/11108810416/job/30862647665#step:5:1125

fix: support params, mag when sharing layer norm in phi-2

---

pyproject.toml
test/test_api.py
test/test_model.py
whittle/models/gpt/model.py

Closes #130 and #129 
Fixes rope for llama-3 models. Using whittle API in eval-harness we can now match llama-3.1-8B performance from huggingface api. 
Added test for llama 3.2

feat: modify rope for llama-3 and support llama-3.2

---

whittle/training_strategies/base_strategy.py

Renames `update` to `__call__` , which all our training strategies actually implement.
---

fix: rename call function

---

.github/workflows/run-examples.yml
.github/workflows/unit-test.yml

this pr switches our `run-examples` and `unit-test` github actions workflows to use `astral-sh/setup-uv` instead of `actions/setup-python`. This cuts the time needed for each workflow roughly in half (~6 mins to ~3 mins)
Closes #148

ci: switching to `uv` for github actions

---

test/test_api.py
test/test_training_strategies.py
whittle/eval/whittle_llms.py
whittle/models/gpt/model.py

The GPT module automatically sets device to `cuda` if CUDA is available. This causes a runtime error, if we move the  model to another device via `.to(device)` after initialization, since the rope cache is still on the original device. 
This fixes also the unit test and handle the handling of devices properly as discussed [here](https://pytorch.org/blog/pytorch-0_4_0-migration-guide/#writing-device-agnostic-code).
---

fix: handle device in GPT model properly

---

test/test_extract.py
whittle/models/gpt/extract.py

https://github.com/whittle-org/whittle/issues/139
Extract sub-network worked only for GPTNeoxMLP, but not for LLamaMLP. I added a function that check for both cases and raises a ValueError if a different MLP class is used.
We should include a test to `test_extract.py` - similar to extracting a smaller `pythia`, but with LLamaMLP
---

feat: add support for LLamaMLP in extract_sub_network

---

test/test_extract.py
whittle/models/gpt/extract.py

https://github.com/whittle-org/whittle/issues/150
Extract weights from norm layers of a subnetwork. Add random init of these weights to the test, since the
default (unit/zero init) passes for uninitialized nets (even without extracting the weights).
`test_extract.py`
---

fix: Extract weights for norm layers, test with random initialization.

---

docs/_scripts/debug_which_page_is_being_rendered.py
examples/profile/profile_flops.py
pyproject.toml
test/test_api.py
test/test_attention.py
test/test_checkpoint_loading.py
test/test_extract.py
test/test_mag.py
test/test_model.py
test/test_parameters.py
test/test_transformer_block.py
whittle/models/gpt/blocks/causal_self_attention.py
whittle/models/gpt/model.py

fix: deprecate flexible mlp heads

---

.github/workflows/docs.yml
.github/workflows/release.yml
whittle/eval/utils.py
whittle/loss/kd_loss.py
whittle/metrics/mag.py
whittle/metrics/parameters.py
whittle/models/gpt/utils.py
whittle/training_strategies/ats.py
whittle/training_strategies/random.py
whittle/training_strategies/random_linear.py
whittle/training_strategies/sandwich.py
whittle/training_strategies/standard.py

Reference Issues/PRs
removes warnings when running  ```mkdocs build --clean --strict```

fix: fixed type hints

---

.github/workflows/release.yml
.github/workflows/run-examples.yml
.github/workflows/unit-test.yml
pyproject.toml

Closes #166
This PR adds support for Python 3.12 by updating the GitHub Actions workflows (`unit-test.yml`, `run-examples.yml`, `pyproject.toml` and `release.yml`). This includes adding Python 3.12 to the testing matrix, ensuring compatibility across supported Python versions.
All tests have been verified to pass for Python 3.12 locally, with minor warnings noted from external dependencies (such as Pydantic and PyTorch) due to Python 3.12's stricter deprecation tracking. These do not affect functionality.
---

ci: add python 3.12 support

---

CONTRIBUTING.md
README.md

updated colab tutorial notebook and git command to clone directory
none
README.md - added link to a new colab tutorial notebook that is aligned with the updates in the API 
CONTRIBUTING.md - git command to clone directory had a typo
none
none
---

fix: colab tutorial notebook and typos

---

pyproject.toml

Current CI fails because of latest `boto3` version which is currently required for Syne Tune. I suggest we put it in here but will remove it again with the next release of Syne Tune.
---

fix: fix dependency versions to avoid breaking CI

---

whittle/models/gpt/model.py

`self.cos` and `self.sin` were not reset when calling `reset_super_network` - fixed
https://github.com/whittle-org/whittle/issues/216
---

fix: Reset the rope cache in reset_super_network

---

pyproject.toml

fix: updating `ruff` config to respect `target-version` for linting

---

test/test_search.py
whittle/eval/whittle_llms.py
whittle/sampling/param_bins.py

There was an off-by-one error - the last bin was counted twice by mistake due to python indexing:
```
for i, value in enumerate(self.values):
if self.bins[i - 1] == self.current_bin_length:
at_max_length += 1
```
The tests did not catch this as they are filling bins from index 0 to -1, and so the last one is always empty.
I added a `continue` in case `i == 0`.
I added a test that checks whether all of them are the same size. Also, the last unfilled bin is now bins[1] instead of bins[-1].
---

fix: off-by-one error in bin sampling

---

examples/profile/profile_flops.py
whittle/metrics/flops.py

Fixes: https://github.com/whittle-org/whittle/issues/276
This PR refines the compute_flops function responsible for estimating floating-point operations (FLOPs) for a GPT model. The following key improvements have been made:
- Switch from DeepSpeed to Lightning: The function now uses the `measure_flops` utility from PyTorch Lightning instead of the DeepSpeed implementation, providing a more lightweight and integrated method for profiling FLOPs.
- Device Flexibility: The function now accepts a device argument, allowing users to specify the device on which to perform the FLOPs calculation (e.g., 'cpu', 'cuda').
- Verbosity: Introduced an optional verbose flag for debug output.

refactor(flops.py): Use Lightning instead of Deepspeed to measure flops

---

test/test_pretrain_super_network.py
whittle/pretrain_super_network.py

This PR resolves #295 
`litgpt.pretrain.save_checkpoint()` uses `litgpt.pretrain.setup(...)` as the reference function to save the hyperparameters which are passed into it. However, there is a mis-match in the function parameters between `litgpt.pretrain.setup(...)` and `whittle.pretrain_super_networks.setup(...)`, with the latter having more parameters such as `accelerator` and `training_strategy`. When these arguments are explicitly passed into the function via the command line (instead of consuming the default values), the script crashes inside `litgpt.pretrain.save_checkpoint()`.
As a workaround, I re-implemented `save_checkpoint()` in Whittle.
The command provided in #295 will now work smoothly.
---
By submitting this pull request, I confirm that you can use, modify, copy, and …

fix: fix crash when checkpointing

---

whittle/evaluate_network.py

This PR addresses #299 
The network evaluation code initially assigns `None` as the default device for the model. However, later, the device is inferred using `torch.cuda.is_available()`. This causes a mismatch in the devices of the weight and data tensors, causing a crash.
This fix infers the correct device in the beginning itself.
The following command will now work (provided `sub_networks/sub_network_0` has a valid checkpoint in it):
```bash
python whittle/evaluate_network.py sub_networks/sub_network_0/ \
--out_dir evaluation/ \
--task arc_easy
```
---

fix(evaluation): fix bug in subnetwork evaluation

---

whittle/full_finetune.py
whittle/lora.py

This PR resolves #301 
See #301 
1. Remove the HF_TOKEN from the environment variables.
2. Run full fine-tuning (assumes that there is a valid checkpoint in `sub_networks/sub_network_0`):
```bash
python /whittle/full_finetune.py sub_networks/sub_network_0 \
--train.max_seq_length 512 \
--access_token <your_access_token> 
```
3. The code will run without errors
---

fix: fix broken HF access token for LlaMaMini

---

whittle/lora.py
whittle/search/search_spaces.py

This PR resolves #303 
The LoRA finetuning of the supernet was crashing because `LoRAQKVLinear.set_sub_network(...)` was being called with a `list[int]` for the parameter `sub_network_n_head` instead of an `int`.
#265 introduced a few new search spaces in  `whittle/search/search_spaces`, including:
1. `SmallSearchSpace`
2. `MediumSearchSpace`
3. `HWGPTBench`
4. `LlamaJoint`
These are imported only in `lora.py`, and can be chosen via the `search_space_type` parameter of `setup`, but all of them crash the run when consumed in the script. `HWGPTBench` is the default.
The reason is that the `cast(config)` method of these search spaces, which is invoked inside the `RandomSampler`, sets `"sub_network_num_heads"` as a list of ints instead of a single int.
To address the issue, a new search space …

fix(lora): fix crash in LoRA finetuning of supernet

---

whittle/metrics/flops.py

This PR resolves #297 
The code would crash with some precisions such as `bf16-mixed` and `16-mixed`. The problem was that `lightning.fabric.utilities.throughput.measure_flops`, which is consumed in `whittle.metrics.flops.compute_flops`, expects a PyTorch model but a PyTorch model wrapped in PyTorch Lightning Fabric was passed into it.
The following script crashes without the fix but now it works
```
python whittle/pretrain_super_network.py EleutherAI/pythia-14m \
--data TinyStories \
--data.data_path ./data \
--tokenizer_dir ~/checkpoints/EleutherAI/pythia-14m/ \
--out_dir pretrained_super_net \
--train.save_interval 5 \
--train.max_tokens 1000000000
```
---
terms of …

fix(measure_flops): fix bug in measuring flops

---

whittle/lora.py
whittle/sampling/grid_samplers.py
whittle/sampling/random_sampler.py
whittle/sampling/samplers.py

This PR resolves #305 
The `StratifiedRandomSampler` requires `params_estimator`, which further requires the initialized GPT model. This isn't available at the time of instantiating the sampler. This fix follows the same paradigm as `FixedParamGridSampler` to handle this.
The parameters being passed into `StratifiedRandomSampler` in `def get_sampler(...)` were also incorrect. Fixed that.
```
python whittle/lora.py sub_networks/sub_network_0/  --out_dir evaluation --train.max_seq_length 512 --sampler.sampling_strategy stratified_random
```
---

fix(lora_finetuning): fix bug when using stratified_random strategy

---

test/test_attention.py
whittle/models/gpt/blocks/causal_self_attention.py

This PR fixes a regression that was introduced in #324 
There are two mistakes in #324.
First, the simplified calculation of the `proj_indices` incorrectly uses the number of heads in the _subnetwork_ to compute the indices, rather than the number of heads in the _supernet_.
Second, this same mistake is repeated in the computation of `qkv_indices` for the case of _grouped query attention_.
A new test case has been added in `tests/test_attention.py` to test for this failure case specifically.
---

fix: fix regression
